version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)

      - echo setting IMAGE_TAG...
      - if [ "$FORCE_IMAGE_TAG" != "" ]; then export IMAGE_TAG=$FORCE_IMAGE_TAG; elif [ "$CODEBUILD_RESOLVED_SOURCE_VERSION" != "" ]; then export IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION; elif [ "$IMAGE_TAG" = "" ]; then export IMAGE_TAG=$(git rev-parse HEAD); fi
  build:
    commands:
      - echo Building the Docker image...
      - cd backend/app
      - docker build ./ -t $IMAGE_REPO:$IMAGE_TAG -f $DOCKERFILE_PATH
      - docker tag $IMAGE_REPO:$IMAGE_TAG 387402613703.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 387402613703.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO:$IMAGE_TAG
