version: 0.2

env:
  secrets-manager:
    DB_USER: rds:username
    DB_PASSWORD: rds:password
    DB_HOST: rds:host
    DB_PORT: rds:port
    DB_NAME: rds:dbname

phases:
  install:
    runtime-versions:
      golang: 1.14
  pre_build:
    commands:
      - mkdir -p ~/.aws
      - echo "[profile todo]" >> ~/.aws/config
      - echo "region = ap-northeast-1" >> ~/.aws/config
      - echo "[todo]" >> ~/.aws/credentials
      - echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
  build:
    commands:
      - cd backend/app
      - make db_migrate
      - export IMAGE_TAG=$(git rev-parse HEAD)
      - make $ENV_NAME deploy
