.PHONY: build run

include scripts/makefile/config/config.mk
include scripts/makefile/db.mk
include scripts/makefile/deploy.mk
include scripts/makefile/docker.mk
include scripts/makefile/test.mk

build:
	go build .

run:
	go run .
