service: todo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-prune-plugin

provider:
  name: aws
  profile: todo

  stage: prod
  region: ap-northeast-1

  memorySize: 3008
  timeout: 900

  vpc:
    securityGroupIds:
      - sg-09dabb1ffa511d35d
    subnetIds:
      - subnet-08091c2900729c379
      - subnet-06521dec4fb148ce4
      - subnet-067c0209c02730662

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "secretsmanager:Describe*"
        - "secretsmanager:Get*"
        - "secretsmanager:List*"
      Resource:
        - "*"

custom:
  environment:
    ENV_NAME: ${env:ENV_NAME}
    LISTEN_PORT: ${env:LISTEN_PORT}
    ALLOW_ORIGIN: ${env:ALLOW_ORIGIN}

    AWS_USER_POOL_ID: ${env:AWS_USER_POOL_ID}
    AWS_USER_POOL_CLIENT_ID: ${env:AWS_USER_POOL_CLIENT_ID}

    DB_SECRET_NAME: ${env:DB_SECRET_NAME}

  prune:
    automatic: true
    number: 3

functions:
  todo:
    image: 387402613703.dkr.ecr.ap-northeast-1.amazonaws.com/todo-list:${env:IMAGE_TAG}
    environment: ${self:custom.environment}
    events:
      - http:
          path: user
          method: post
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
      - http:
          path: todo
          method: get
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
      - http:
          path: todo
          method: post
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
      - http:
          path: todo
          method: put
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
      - http:
          path: todo
          method: delete
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
      - http:
          path: todo/list
          method: get
          cors:
            origins:
              - https://d2semoivot4v0t.cloudfront.net
            allowCredentials: false
